name: Daily README Update

on:
  # Run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Run on push to main branch (but skip if commit message contains 'Auto-update')
  push:
    branches:
    - main

permissions:
  contents: write
  actions: read

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    # Skip if the push was from this action itself
    if: "!contains(github.event.head_commit.message, 'Auto-update README timestamp')"
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      # Set up Git configuration
      - name: Setup Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
      # Update timestamp in README
      - name: Update README timestamp
        run: |
          # Get current UTC timestamp
          TIMESTAMP=$(date -u '+%a %b %d %H:%M:%S UTC %Y')
          
          # Check if README.md exists
          if [ ! -f "README.md" ]; then
            echo "README.md not found!"
            exit 1
          fi
          
          # Remove any existing timestamp lines
          sed -i '/<!-- Profile updated:/d' README.md
          
          # Add new timestamp at the end
          echo "<!-- Profile updated: $TIMESTAMP -->" >> README.md
          
      # Check if there are changes
      - name: Check for changes
        id: verify-diff
        run: |
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          
      # Commit and push changes
      - name: Commit changes
        if: steps.verify-diff.outputs.changed == 'true'
        run: |
          git commit -m "Auto-update README timestamp"
          git push origin main
