name: Daily Profile Update

on:
  # run automatically every day at 2 AM UTC
  schedule:
    - cron: "0 2 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push to main branch
  push:
    branches:
    - master
    - main

jobs:
  update-profile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      # Update README timestamp to force cache refresh
      - name: Update README timestamp
        run: |
          # Add a hidden comment with current timestamp to force cache refresh
          echo "<!-- Profile updated: $(date) -->" >> README.md
          
      # Commit changes if any
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "Daily profile update - $(date)"
            git push
          fi
