name: Profile README Generator

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: "0 0 * * *"
  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-profile:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Update README
        run: |
          # Update the timestamp
          TIMESTAMP=$(date -u '+%a %b %d %H:%M:%S UTC %Y')
          
          # Check if README.md exists
          if [ -f "README.md" ]; then
            # Create a backup
            cp README.md README.md.bak
            
            # Remove old timestamp lines
            grep -v "<!-- Profile updated:" README.md.bak > README.md
            
            # Add new timestamp
            echo "<!-- Profile updated: $TIMESTAMP -->" >> README.md
            
            # Check if there are changes
            if ! git diff --quiet README.md; then
              git add README.md
              git commit -m "Auto-update profile README - $TIMESTAMP"
              git push
              echo "README updated successfully"
            else
              echo "No changes to commit"
            fi
            
            # Clean up
            rm -f README.md.bak
          else
            echo "README.md not found!"
            exit 1
          fi
